(defparameter *tu1*
  '((:I . 310788)
    (:BI-TEXT
     (:SOURCE
      . "\"Yeah, a lot of places do that nowadays. OK, I just want one pizza, you know just to try them out.\"")
     (:TARGET
      . "อื้ม เดี๋ยวนี้เค้าทํากันเยอะนะครับ โอเค อยากได้เป็นพิซซ่าถาดนึงครับ เอามาลองดูน่ะครับ"))
    (:BI-RTOKS
     (:SOURCE ((:S . 1) (:E . 5) (:TEXT . "Yeah"))
      ((:S . 5) (:E . 6) (:TEXT . ",")) ((:S . 7) (:E . 8) (:TEXT . "a"))
      ((:S . 9) (:E . 12) (:TEXT . "lot")) ((:S . 13) (:E . 15) (:TEXT . "of"))
      ((:S . 16) (:E . 22) (:TEXT . "places"))
      ((:S . 23) (:E . 25) (:TEXT . "do")) ((:S . 26) (:E . 30) (:TEXT . "that"))
      ((:S . 31) (:E . 39) (:TEXT . "nowadays"))
      ((:S . 39) (:E . 40) (:TEXT . ".")) ((:S . 41) (:E . 43) (:TEXT . "OK"))
      ((:S . 43) (:E . 44) (:TEXT . ",")) ((:S . 45) (:E . 46) (:TEXT . "I"))
      ((:S . 47) (:E . 51) (:TEXT . "just"))
      ((:S . 52) (:E . 56) (:TEXT . "want")) ((:S . 57) (:E . 60) (:TEXT . "one"))
      ((:S . 61) (:E . 66) (:TEXT . "pizza")) ((:S . 66) (:E . 67) (:TEXT . ","))
      ((:S . 68) (:E . 71) (:TEXT . "you")) ((:S . 72) (:E . 76) (:TEXT . "know"))
      ((:S . 77) (:E . 81) (:TEXT . "just")) ((:S . 82) (:E . 84) (:TEXT . "to"))
      ((:S . 85) (:E . 88) (:TEXT . "try")) ((:S . 89) (:E . 93) (:TEXT . "them"))
      ((:S . 94) (:E . 97) (:TEXT . "out")) ((:S . 97) (:E . 98) (:TEXT . ".")))
     (:TARGET ((:S . 0) (:E . 4) (:TEXT . "อื้ม"))
      ((:S . 5) (:E . 14) (:TEXT . "เดี๋ยวนี้"))
      ((:S . 14) (:E . 18) (:TEXT . "เค้า")) ((:S . 18) (:E . 21) (:TEXT . "ทํา"))
      ((:S . 21) (:E . 24) (:TEXT . "กัน")) ((:S . 24) (:E . 26) (:TEXT . "เย"))
      ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))
      ((:S . 30) (:E . 34) (:TEXT . "ครับ"))
      ((:S . 35) (:E . 39) (:TEXT . "โอเค"))
      ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
      ((:S . 47) (:E . 51) (:TEXT . "เป็น"))
      ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))
      ((:S . 57) (:E . 60) (:TEXT . "ถาด")) ((:S . 60) (:E . 63) (:TEXT . "นึง"))
      ((:S . 63) (:E . 67) (:TEXT . "ครับ")) ((:S . 68) (:E . 71) (:TEXT . "เอา"))
      ((:S . 71) (:E . 73) (:TEXT . "มา")) ((:S . 73) (:E . 78) (:TEXT . "ลองดู"))
      ((:S . 78) (:E . 81) (:TEXT . "น่ะ"))
      ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
    (:TREE
     (:BI-SNODE
      (:SOURCE
       ((:S . 0) (:E . 99)
	(:TEXT
	 . "\"Yeah, a lot of places do that nowadays. OK, I just want one pizza, you know just to try them out.\"")))
      (:TARGET
       ((:S . 0) (:E . 85)
	(:TEXT
	 . "อื้ม เดี๋ยวนี้เค้าทํากันเยอะนะครับ โอเค อยากได้เป็นพิซซ่าถาดนึงครับ เอามาลองดูน่ะครับ"))))
     (:CHILDREN
      ((:BI-SNODE
	(:SOURCE
	 ((:S . 1) (:E . 40) (:TEXT . "Yeah, a lot of places do that nowadays.")))
	(:TARGET
	 ((:S . 0) (:E . 34) (:TEXT . "อื้ม เดี๋ยวนี้เค้าทํากันเยอะนะครับ"))))
       (:CHILDREN))
      ((:BI-SNODE
	(:SOURCE ((:S . 77) (:E . 98) (:TEXT . "just to try them out."))
	 ((:S . 41) (:E . 66) (:TEXT . "OK, I just want one pizza"))
	 ((:S . 68) (:E . 71) (:TEXT . "you")))
	(:TARGET
	 ((:S . 35) (:E . 78)
		    (:TEXT . "โอเค อยากได้เป็นพิซซ่าถาดนึงครับ เอามาลองดู"))
	 ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
       (:CHILDREN
	((:BI-SNODE (:SOURCE ((:S . 41) (:E . 56) (:TEXT . "OK, I just want")))
		    (:TARGET ((:S . 35) (:E . 51) (:TEXT . "โอเค อยากได้เป็น"))))
	 (:CHILDREN))
	((:BI-SNODE
	  (:SOURCE ((:S . 77) (:E . 98) (:TEXT . "just to try them out."))
		   ((:S . 57) (:E . 66) (:TEXT . "one pizza"))
		   ((:S . 68) (:E . 71) (:TEXT . "you")))
	  (:TARGET ((:S . 51) (:E . 78) (:TEXT . "พิซซ่าถาดนึงครับ เอามาลองดู"))
		   ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
	 (:CHILDREN
	  ((:BI-SNODE
	    (:SOURCE ((:S . 57) (:E . 66) (:TEXT . "one pizza"))
		     ((:S . 68) (:E . 71) (:TEXT . "you")))
	    (:TARGET ((:S . 51) (:E . 63) (:TEXT . "พิซซ่าถาดนึง"))
		     ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
	   (:CHILDREN
	    ((:BI-SNODE (:SOURCE ((:S . 57) (:E . 66) (:TEXT . "one pizza")))
			(:TARGET ((:S . 51) (:E . 63) (:TEXT . "พิซซ่าถาดนึง"))))
	     (:CHILDREN))
	    ((:BI-SNODE (:SOURCE ((:S . 68) (:E . 71) (:TEXT . "you")))
			(:TARGET ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
	     (:CHILDREN))))
	  ((:BI-SNODE
	    (:SOURCE ((:S . 77) (:E . 98) (:TEXT . "just to try them out.")))
	    (:TARGET ((:S . 63) (:E . 78) (:TEXT . "ครับ เอามาลองดู"))))
	   (:CHILDREN))))))))
    (:LINKS ((:SOURCE . 0) (:TARGET . 0)) ((:SOURCE . 0) (:TARGET . 1))
     ((:SOURCE . 3) (:TARGET . 5)) ((:SOURCE . 3) (:TARGET . 6))
     ((:SOURCE . 4) (:TARGET . 4)) ((:SOURCE . 6) (:TARGET . 2))
     ((:SOURCE . 6) (:TARGET . 3)) ((:SOURCE . 9) (:TARGET . 7))
     ((:SOURCE . 10) (:TARGET . 8)) ((:SOURCE . 13) (:TARGET . 10))
     ((:SOURCE . 14) (:TARGET . 9)) ((:SOURCE . 15) (:TARGET . 13))
     ((:SOURCE . 16) (:TARGET . 11)) ((:SOURCE . 17) (:TARGET . 22))
     ((:SOURCE . 18) (:TARGET . 19)) ((:SOURCE . 19) (:TARGET . 25))
     ((:SOURCE . 20) (:TARGET . 15)) ((:SOURCE . 21) (:TARGET . 16))
     ((:SOURCE . 22) (:TARGET . 17)) ((:SOURCE . 25) (:TARGET . 14)))
    (:INITIAL-PHRASE-PAIRS
     ((:SOURCE ((:S . 1) (:E . 5) (:TEXT . "Yeah")))
      (:TARGET ((:S . 0) (:E . 4) (:TEXT . "อื้ม"))
       ((:S . 5) (:E . 14) (:TEXT . "เดี๋ยวนี้"))))
     ((:SOURCE ((:S . 1) (:E . 5) (:TEXT . "Yeah"))
       ((:S . 5) (:E . 6) (:TEXT . ",")) ((:S . 7) (:E . 8) (:TEXT . "a"))
       ((:S . 9) (:E . 12) (:TEXT . "lot")) ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")))
      (:TARGET ((:S . 0) (:E . 4) (:TEXT . "อื้ม"))
       ((:S . 5) (:E . 14) (:TEXT . "เดี๋ยวนี้"))
       ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา")) ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย"))
       ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))))
     ((:SOURCE ((:S . 1) (:E . 5) (:TEXT . "Yeah"))
       ((:S . 5) (:E . 6) (:TEXT . ",")) ((:S . 7) (:E . 8) (:TEXT . "a"))
       ((:S . 9) (:E . 12) (:TEXT . "lot")) ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")) ((:S . 26) (:E . 30) (:TEXT . "that"))
       ((:S . 31) (:E . 39) (:TEXT . "nowadays"))
       ((:S . 39) (:E . 40) (:TEXT . ".")))
      (:TARGET ((:S . 0) (:E . 4) (:TEXT . "อื้ม"))
       ((:S . 5) (:E . 14) (:TEXT . "เดี๋ยวนี้"))
       ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา")) ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย")) ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))
       ((:S . 30) (:E . 34) (:TEXT . "ครับ"))))
     ((:SOURCE ((:S . 9) (:E . 12) (:TEXT . "lot")))
      (:TARGET ((:S . 24) (:E . 26) (:TEXT . "เย"))
       ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))))
     ((:SOURCE ((:S . 9) (:E . 12) (:TEXT . "lot"))
       ((:S . 13) (:E . 15) (:TEXT . "of")))
      (:TARGET ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย"))
       ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))))
     ((:SOURCE ((:S . 9) (:E . 12) (:TEXT . "lot"))
       ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")))
      (:TARGET ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา")) ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย"))
       ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))))
     ((:SOURCE ((:S . 9) (:E . 12) (:TEXT . "lot"))
       ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")) ((:S . 26) (:E . 30) (:TEXT . "that"))
       ((:S . 31) (:E . 39) (:TEXT . "nowadays"))
       ((:S . 39) (:E . 40) (:TEXT . ".")))
      (:TARGET ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา")) ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย")) ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))
       ((:S . 30) (:E . 34) (:TEXT . "ครับ"))))
     ((:SOURCE ((:S . 9) (:E . 12) (:TEXT . "lot"))
       ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")) ((:S . 26) (:E . 30) (:TEXT . "that"))
       ((:S . 31) (:E . 39) (:TEXT . "nowadays"))
       ((:S . 39) (:E . 40) (:TEXT . ".")) ((:S . 41) (:E . 43) (:TEXT . "OK")))
      (:TARGET ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา")) ((:S . 21) (:E . 24) (:TEXT . "กัน"))
       ((:S . 24) (:E . 26) (:TEXT . "เย")) ((:S . 26) (:E . 30) (:TEXT . "อะนะ"))
       ((:S . 30) (:E . 34) (:TEXT . "ครับ"))
       ((:S . 35) (:E . 39) (:TEXT . "โอเค"))))
     ((:SOURCE ((:S . 13) (:E . 15) (:TEXT . "of")))
      (:TARGET ((:S . 21) (:E . 24) (:TEXT . "กัน"))))
     ((:SOURCE ((:S . 13) (:E . 15) (:TEXT . "of"))
       ((:S . 16) (:E . 22) (:TEXT . "places"))
       ((:S . 23) (:E . 25) (:TEXT . "do")))
      (:TARGET ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา"))
       ((:S . 21) (:E . 24) (:TEXT . "กัน"))))
     ((:SOURCE ((:S . 23) (:E . 25) (:TEXT . "do")))
      (:TARGET ((:S . 14) (:E . 18) (:TEXT . "เค้า"))
       ((:S . 18) (:E . 21) (:TEXT . "ทํา"))))
     ((:SOURCE ((:S . 39) (:E . 40) (:TEXT . ".")))
      (:TARGET ((:S . 30) (:E . 34) (:TEXT . "ครับ"))))
     ((:SOURCE ((:S . 39) (:E . 40) (:TEXT . "."))
       ((:S . 41) (:E . 43) (:TEXT . "OK")))
      (:TARGET ((:S . 30) (:E . 34) (:TEXT . "ครับ"))
       ((:S . 35) (:E . 39) (:TEXT . "โอเค"))))
     ((:SOURCE ((:S . 39) (:E . 40) (:TEXT . "."))
       ((:S . 41) (:E . 43) (:TEXT . "OK")) ((:S . 43) (:E . 44) (:TEXT . ","))
       ((:S . 45) (:E . 46) (:TEXT . "I")) ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want")))
      (:TARGET ((:S . 30) (:E . 34) (:TEXT . "ครับ"))
       ((:S . 35) (:E . 39) (:TEXT . "โอเค"))
       ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))))
     ((:SOURCE ((:S . 39) (:E . 40) (:TEXT . "."))
       ((:S . 41) (:E . 43) (:TEXT . "OK")) ((:S . 43) (:E . 44) (:TEXT . ","))
       ((:S . 45) (:E . 46) (:TEXT . "I")) ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want"))
       ((:S . 57) (:E . 60) (:TEXT . "one"))
       ((:S . 61) (:E . 66) (:TEXT . "pizza")))
      (:TARGET ((:S . 30) (:E . 34) (:TEXT . "ครับ"))
       ((:S . 35) (:E . 39) (:TEXT . "โอเค"))
       ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))
       ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))
       ((:S . 57) (:E . 60) (:TEXT . "ถาด"))
       ((:S . 60) (:E . 63) (:TEXT . "นึง"))))
     ((:SOURCE ((:S . 41) (:E . 43) (:TEXT . "OK")))
      (:TARGET ((:S . 35) (:E . 39) (:TEXT . "โอเค"))))
     ((:SOURCE ((:S . 41) (:E . 43) (:TEXT . "OK"))
       ((:S . 43) (:E . 44) (:TEXT . ",")) ((:S . 45) (:E . 46) (:TEXT . "I"))
       ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want")))
      (:TARGET ((:S . 35) (:E . 39) (:TEXT . "โอเค"))
       ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))))
     ((:SOURCE ((:S . 41) (:E . 43) (:TEXT . "OK"))
       ((:S . 43) (:E . 44) (:TEXT . ",")) ((:S . 45) (:E . 46) (:TEXT . "I"))
       ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want"))
       ((:S . 57) (:E . 60) (:TEXT . "one"))
       ((:S . 61) (:E . 66) (:TEXT . "pizza")))
      (:TARGET ((:S . 35) (:E . 39) (:TEXT . "โอเค"))
       ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))
       ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))
       ((:S . 57) (:E . 60) (:TEXT . "ถาด"))
       ((:S . 60) (:E . 63) (:TEXT . "นึง"))))
     ((:SOURCE ((:S . 47) (:E . 51) (:TEXT . "just")))
      (:TARGET ((:S . 47) (:E . 51) (:TEXT . "เป็น"))))
     ((:SOURCE ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want")))
      (:TARGET ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))))
     ((:SOURCE ((:S . 47) (:E . 51) (:TEXT . "just"))
       ((:S . 52) (:E . 56) (:TEXT . "want"))
       ((:S . 57) (:E . 60) (:TEXT . "one"))
       ((:S . 61) (:E . 66) (:TEXT . "pizza")))
      (:TARGET ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))
       ((:S . 47) (:E . 51) (:TEXT . "เป็น"))
       ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))
       ((:S . 57) (:E . 60) (:TEXT . "ถาด"))
       ((:S . 60) (:E . 63) (:TEXT . "นึง"))))
     ((:SOURCE ((:S . 52) (:E . 56) (:TEXT . "want")))
      (:TARGET ((:S . 40) (:E . 47) (:TEXT . "อยากได้"))))
     ((:SOURCE ((:S . 57) (:E . 60) (:TEXT . "one")))
      (:TARGET ((:S . 60) (:E . 63) (:TEXT . "นึง"))))
     ((:SOURCE ((:S . 57) (:E . 60) (:TEXT . "one"))
       ((:S . 61) (:E . 66) (:TEXT . "pizza")))
      (:TARGET ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))
       ((:S . 57) (:E . 60) (:TEXT . "ถาด"))
       ((:S . 60) (:E . 63) (:TEXT . "นึง"))))
     ((:SOURCE ((:S . 61) (:E . 66) (:TEXT . "pizza")))
      (:TARGET ((:S . 51) (:E . 57) (:TEXT . "พิซซ่า"))))
     ((:SOURCE ((:S . 68) (:E . 71) (:TEXT . "you")))
      (:TARGET ((:S . 81) (:E . 85) (:TEXT . "ครับ"))))
     ((:SOURCE ((:S . 77) (:E . 81) (:TEXT . "just")))
      (:TARGET ((:S . 68) (:E . 71) (:TEXT . "เอา"))))
     ((:SOURCE ((:S . 77) (:E . 81) (:TEXT . "just"))
       ((:S . 82) (:E . 84) (:TEXT . "to")))
      (:TARGET ((:S . 68) (:E . 71) (:TEXT . "เอา"))
       ((:S . 71) (:E . 73) (:TEXT . "มา"))))
     ((:SOURCE ((:S . 77) (:E . 81) (:TEXT . "just"))
       ((:S . 82) (:E . 84) (:TEXT . "to")) ((:S . 85) (:E . 88) (:TEXT . "try")))
      (:TARGET ((:S . 68) (:E . 71) (:TEXT . "เอา"))
       ((:S . 71) (:E . 73) (:TEXT . "มา"))
       ((:S . 73) (:E . 78) (:TEXT . "ลองดู"))))
     ((:SOURCE ((:S . 77) (:E . 81) (:TEXT . "just"))
       ((:S . 82) (:E . 84) (:TEXT . "to")) ((:S . 85) (:E . 88) (:TEXT . "try"))
       ((:S . 89) (:E . 93) (:TEXT . "them"))
       ((:S . 94) (:E . 97) (:TEXT . "out")) ((:S . 97) (:E . 98) (:TEXT . ".")))
      (:TARGET ((:S . 63) (:E . 67) (:TEXT . "ครับ"))
       ((:S . 68) (:E . 71) (:TEXT . "เอา")) ((:S . 71) (:E . 73) (:TEXT . "มา"))
       ((:S . 73) (:E . 78) (:TEXT . "ลองดู"))))
     ((:SOURCE ((:S . 82) (:E . 84) (:TEXT . "to")))
      (:TARGET ((:S . 71) (:E . 73) (:TEXT . "มา"))))
     ((:SOURCE ((:S . 82) (:E . 84) (:TEXT . "to"))
       ((:S . 85) (:E . 88) (:TEXT . "try")))
      (:TARGET ((:S . 71) (:E . 73) (:TEXT . "มา"))
       ((:S . 73) (:E . 78) (:TEXT . "ลองดู"))))
     ((:SOURCE ((:S . 85) (:E . 88) (:TEXT . "try")))
      (:TARGET ((:S . 73) (:E . 78) (:TEXT . "ลองดู"))))
     ((:SOURCE ((:S . 97) (:E . 98) (:TEXT . ".")))
      (:TARGET ((:S . 63) (:E . 67) (:TEXT . "ครับ")))))
    (:L-ANALYSIS ((:E . 5) (:S . 1) (:TAG "Yeah"))
     ((:E . 15) (:S . 7) (:TAG "a lot of" "det" "qnt" "sp"))
     ((:E . 22) (:S . 16) (:TAG "place" "n" "pl"))
     ((:E . 25) (:S . 23) (:TAG "do" "vbdo" "pres"))
     ((:E . 30) (:S . 26) (:TAG "that" "rel" "an" "mf" "sp"))
     ((:E . 39) (:S . 31) (:TAG "nowadays" "adv"))
     ((:E . 40) (:S . 39) (:TAG "." "sent")) ((:E . 43) (:S . 41) (:TAG "OK"))
     ((:E . 46) (:S . 45) (:TAG "prpers" "prn" "subj" "p1" "mf" "sg"))
     ((:E . 51) (:S . 47) (:TAG "just" "adv"))
     ((:E . 56) (:S . 52) (:TAG "want" "vblex" "pres"))
     ((:E . 60) (:S . 57) (:TAG "one" "num" "sg"))
     ((:E . 66) (:S . 61) (:TAG "pizza" "n" "sg"))
     ((:E . 71) (:S . 68) (:TAG "prpers" "prn" "subj" "p2" "mf" "sp"))
     ((:E . 76) (:S . 72) (:TAG "know" "vblex" "pres"))
     ((:E . 81) (:S . 77) (:TAG "just" "adv"))
     ((:E . 84) (:S . 82) (:TAG "to" "pr"))
     ((:E . 88) (:S . 85) (:TAG "try" "vblex" "pres"))
     ((:E . 93) (:S . 89) (:TAG "prpers" "prn" "obj" "p3" "mf" "pl"))
     ((:E . 97) (:S . 94) (:TAG "out" "adv"))
     ((:E . 98) (:S . 97) (:TAG "." "sent")))))
